import React from 'react'

// SVG path constants (inlined from autogenerated Figma modules)
const PATH_GITHUB = "M5.16679 12.5179C1.83345 13.5179 1.83345 10.8512 0.500118 10.5179M9.83345 14.5179V11.9379C9.85846 11.62 9.81551 11.3004 9.70746 11.0004C9.59941 10.7004 9.42874 10.4268 9.20679 10.1979C11.3001 9.96453 13.5001 9.1712 13.5001 5.5312C13.4999 4.60041 13.1419 3.70533 12.5001 3.0312C12.804 2.21687 12.7825 1.31676 12.4401 0.517862C12.4401 0.517862 11.6535 0.284529 9.83345 1.50453C8.30546 1.09041 6.69478 1.09041 5.16679 1.50453C3.34678 0.284529 2.56012 0.517862 2.56012 0.517862C2.2177 1.31676 2.19621 2.21687 2.50012 3.0312C1.85354 3.71033 1.49513 4.6135 1.50012 5.5512C1.50012 9.16453 3.70012 9.95786 5.79345 10.2179C5.57412 10.4445 5.40496 10.7148 5.29699 11.0111C5.18902 11.3075 5.14466 11.6232 5.16679 11.9379V14.5179"
const PATH_POSTER = "M11.1667 5.16667L6.5 0.5H1.83333C1.47971 0.5 1.14057 0.640476 0.890524 0.890524C0.640476 1.14057 0.5 1.47971 0.5 1.83333V12.5C0.5 12.8536 0.640476 13.1928 0.890524 13.4428C1.14057 13.6929 1.47971 13.8333 1.83333 13.8333H9.83333C10.187 13.8333 10.5261 13.6929 10.7761 13.4428C11.0262 13.1928 11.1667 12.8536 11.1667 12.5V5.16667ZM6.5 0.5V5.16667H11.1667"
const PATH_LIVE = "M7.16667 4.5C5.69391 4.5 4.5 5.69391 4.5 7.16667C4.5 8.63943 5.69391 9.83333 7.16667 9.83333C8.63943 9.83333 9.83333 8.63943 9.83333 7.16667C9.83333 5.69391 8.63943 4.5 7.16667 4.5ZM7.16667 4.5H13.28M1.8 3.20667L4.86 8.5M6.42 13.7933L9.47333 8.5M13.8333 7.16667C13.8333 10.8486 10.8486 13.8333 7.16667 13.8333C3.48477 13.8333 0.5 10.8486 0.5 7.16667C0.5 3.48477 3.48477 0.5 7.16667 0.5C10.8486 0.5 13.8333 3.48477 13.8333 7.16667Z"
const PATH_TIMELINE_DOT = "M8.90699 17.814C13.8262 17.814 17.814 13.8262 17.814 8.90699C17.814 3.98779 13.8262 0 8.90699 0C3.98779 0 0 3.98779 0 8.90699C0 13.8262 3.98779 17.814 8.90699 17.814Z"

// Icon component prop types
type IconProps = React.SVGProps<SVGSVGElement> & { 
  strokeColor?: string
  fillColor?: string
}

// GitHub icon (outline)
export function GithubIcon({ strokeColor = 'var(--stroke-0, #6750A4)', className, ...props }: IconProps) {
  return (
    <svg className={className} fill="none" preserveAspectRatio="xMidYMid meet" viewBox="-1 -1 16 16" {...props}>
      <path d={PATH_GITHUB} stroke={strokeColor} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// Poster/file icon (outline)
export function PosterIcon({ strokeColor = 'var(--stroke-0, #6750A4)', className, ...props }: IconProps) {
  return (
    <svg className={className} fill="none" preserveAspectRatio="xMidYMid meet" viewBox="-1 -1 16 17" {...props}>
      <path d={PATH_POSTER} stroke={strokeColor} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// Live/browser icon (outline)
export function LiveIcon({ strokeColor = 'var(--stroke-0, #6750A4)', className, ...props }: IconProps) {
  return (
    <svg className={className} fill="none" preserveAspectRatio="xMidYMid meet" viewBox="-1 -1 16 16" {...props}>
      <path d={PATH_LIVE} stroke={strokeColor} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// Timeline dot icon (filled)
export function TimelineDotIcon({ fillColor = 'var(--fill-0, #6750A4)', className, ...props }: IconProps) {
  return (
    <svg className={className} fill="none" preserveAspectRatio="xMidYMid meet" viewBox="0 0 17.814 17.814" {...props}>
      <path d={PATH_TIMELINE_DOT} fill={fillColor} />
    </svg>
  )
}

